### ISSUE TITLE
Missing d in the repo name

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/com.github.alecaddd.sequeler#1]
The repo name should be `alecaddd` instead of `alecadd`

**Comment by bilelmoussaoui** [comment]
@alecaddd Would you be interested to have write access to the repo?

**Comment by nedrichards** [comment]
Renamed and invited.

**Comment by bilelmoussaoui** [comment]
Will that trigger a build automatically?

**Comment by Alecaddd** [comment]
Hi, thanks for the port to flathub and the invite.
I don't know anything about flathub, and I'm not sure if I'll ever be able to help with this port in any way, but nonetheless, it's exciting 😄

**Comment by TingPing** [comment]
I triggered the build: https://flathub.org/builds/#/builders/2/builds/419

**Comment by TingPing** [comment]
@Alecaddd For the most part just test new releases and bump versions.
