### ISSUE TITLE
GNOME 40 no longer supported?

### ISSUE THREAD

**Issue by dineshdb** [flathub/com.github.alecaddd.sequeler#30]
When I try to install this app, I get following error:
```
The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
```

Could the maintainers update the dependency?

I tried updating both the gnome version and juno version and it greeted with intl-tool is too old message.

When I updated only gnome, I get:
``ModuleNotFoundError: No module named 'giscanner._giscanner'``

**Comment by VinnyFonseca** [comment]
Still happening 24 Nov

**Comment by bilelmoussaoui** [comment]
I will update it this weekend
