### ISSUE TITLE
Flatkak file chooser is not working

### ISSUE THREAD

**Issue by ohaessler** [flathub/com.github.alecaddd.sequeler#8]
On RHEL the file chooser is not working (for example to choose an SQLite database. Error:

flatpak run com.github.alecaddd.sequeler
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "unity-gtk-module"

(Sequeler:3): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'text != NULL' failed

(Sequeler:3): Gtk-WARNING **: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

**Comment by TingPing** [comment]
Install `xdg-desktop-portal-gtk` on the host.

**Comment by ohaessler** [comment]
Thanks, that was the solution.
